#!/usr/bin/env python3
"""Assemble the per-condition inter-judge agreement table for the decomposition.

`compute_inter_judge_agreement.py` writes fixed filenames, so each decomposition
condition is scanned into its own directory:

    python scripts/compute_inter_judge_agreement.py \\
        --personas decomp_b_xml_objective \\
        --tables-dir tables/decomposition/alpha_decomp_b_xml_objective

This script collects those directories into one table. It exists instead of a
hand-written markdown file for one reason: every number in it is read from the
CSV that produced it, so the prose cannot drift from the data the way a
transcribed table can.

**What this table is not.** Each condition's alpha is conditioned on that
condition alone. The four are never pooled with each other, and none of them is
pooled with the published figures -- not the alpha, not the design effects, not
the 35,416-item count, not the judge self-preference DiD. The published pooled
alpha (0.706) is computed across baseline + good_persona + bad_persona together
and is *arithmetically* higher than any single condition's alpha for a reason
that has nothing to do with judge quality: pooling conditions widens the score
range, which enlarges alpha's expected-disagreement denominator. The only
like-for-like reference is therefore the published *per-persona* breakdown,
which is reproduced here from `tables/inter_judge_agreement_by_persona.csv` and
is still not a controlled comparison -- it covers fifteen models where the
decomposition covers eleven.

Run from repo root:
    python scripts/assemble_decomposition_alpha.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from humanebench import decomposition as dc  # noqa: E402

# The published headline CI: scenarios are the honest cluster unit, because one
# prompt's response text drives every judge's score for that prompt.
PRIMARY_SPEC = "cluster_input_id"


def read_condition(directory: Path) -> dict | None:
    path = directory / "inter_judge_agreement.csv"
    if not path.is_file():
        return None
    row = pd.read_csv(path).iloc[0]
    return {
        "n_items": int(row["n_items_included"]),
        "alpha_ord": float(row["alpha_ord"]),
        "alpha_ord_lo": float(row[f"alpha_ord_{PRIMARY_SPEC}_ci_lower"]),
        "alpha_ord_hi": float(row[f"alpha_ord_{PRIMARY_SPEC}_ci_upper"]),
        "alpha_bin": float(row["alpha_bin"]),
        "alpha_bin_lo": float(row[f"alpha_bin_{PRIMARY_SPEC}_ci_lower"]),
        "alpha_bin_hi": float(row[f"alpha_bin_{PRIMARY_SPEC}_ci_upper"]),
        "sign_disagreement": float(row["sign_disagreement_rate"]),
        "n_clusters": int(row[f"alpha_ord_{PRIMARY_SPEC}_n_clusters"]),
        "design_effect": float(row[f"alpha_ord_{PRIMARY_SPEC}_design_effect"]),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--alpha-root", type=Path,
                    default=REPO_ROOT / "tables" / "decomposition")
    ap.add_argument("--by-persona-csv", type=Path,
                    default=REPO_ROOT / "tables"
                    / "inter_judge_agreement_by_persona.csv")
    ap.add_argument("--out", type=Path,
                    default=REPO_ROOT / "tables" / "decomposition"
                    / "alpha_by_condition.md")
    args = ap.parse_args()

    found, missing = {}, []
    for cond in dc.CONDITIONS:
        stats = read_condition(args.alpha_root / f"alpha_{cond.task_type}")
        if stats is None:
            missing.append(cond.label)
        else:
            found[cond.label] = stats
    if not found:
        raise SystemExit(
            f"no per-condition agreement directories under {args.alpha_root}; "
            "run compute_inter_judge_agreement.py --personas <condition> first"
        )

    L: list[str] = ["# Inter-judge agreement, by decomposition condition\n"]
    L.append(
        "Generated by `scripts/assemble_decomposition_alpha.py` from one "
        "`compute_inter_judge_agreement.py` run per condition. CIs are the "
        "primary published spec: cluster bootstrap on `input_id` (scenarios), "
        "1000 replicates.\n"
    )
    L.append(
        "**Each row stands alone.** These alphas are not pooled with each "
        "other and not pooled with any published figure. The published pooled "
        "α, design effects, 35,416-item count and judge self-preference DiD "
        "remain conditioned on baseline + good_persona + bad_persona and are "
        "unchanged by anything here.\n"
    )
    if missing:
        L.append(
            f"**Conditions absent from this table:** {', '.join(missing)} — no "
            "agreement directory on disk, so they are excluded rather than "
            "estimated.\n"
        )

    L.append("| Condition | n scored items | scenarios | α ordinal [95% CI] "
             "| α binary [95% CI] | sign-disagreement | design effect |")
    L.append("|---|---:|---:|---|---|---:|---:|")
    for label, s in found.items():
        L.append(
            f"| {label} | {s['n_items']:,} | {s['n_clusters']:,} | "
            f"{s['alpha_ord']:.3f} [{s['alpha_ord_lo']:.3f}, {s['alpha_ord_hi']:.3f}] | "
            f"{s['alpha_bin']:.3f} [{s['alpha_bin_lo']:.3f}, {s['alpha_bin_hi']:.3f}] | "
            f"{s['sign_disagreement']:.1%} | {s['design_effect']:.2f} |"
        )
    L.append("")

    if args.by_persona_csv.is_file():
        ref = pd.read_csv(args.by_persona_csv)
        L.append("## Reference: the published per-persona breakdown\n")
        L.append(
            "Reproduced unchanged from `tables/inter_judge_agreement_by_persona"
            ".csv`. It is the only like-for-like reference, because it is also "
            "one condition at a time. It is **not** a controlled comparison: it "
            "covers the published fifteen models, the decomposition covers "
            "eleven, and no CIs were computed for the per-persona split.\n"
        )
        L.append("| Persona | n scored items | α ordinal | α binary | sign-disagreement |")
        L.append("|---|---:|---:|---:|---:|")
        for r in ref.to_dict("records"):
            L.append(
                f"| {r['persona']} | {int(r['n_items']):,} | "
                f"{r['alpha_ord']:.3f} | {r['alpha_bin']:.3f} | "
                f"{r['sign_disagreement_rate']:.1%} |"
            )
        L.append("")

        # The one comparison the table supports, stated as a range rather than
        # as a test: no CI exists on the per-persona rows to test against.
        lo = min(s["alpha_ord"] for s in found.values())
        hi = max(s["alpha_ord"] for s in found.values())
        by_persona = dict(zip(ref["persona"], ref["alpha_ord"]))
        base = by_persona.get("baseline")
        anchor = by_persona.get(dc.ANCHOR_PERSONA)
        if base is not None and anchor is not None:
            between = base <= lo and hi <= anchor
            L.append(
                f"The decomposition conditions run α_ordinal "
                f"{lo:.3f}–{hi:.3f}, against {base:.3f} for baseline and "
                f"{anchor:.3f} for the adversarial persona"
                + (
                    " — between the two, which is where an arm that lands "
                    "between them on the score itself would be expected to sit. "
                    "Judges agree most where responses are unambiguous, and the "
                    "objective-only arms are less unambiguous than A. This is "
                    "consistent with the attenuation the score contrasts "
                    "measure; it is a description of the same fact through a "
                    "second channel, not independent evidence for it."
                    if between else
                    ". No ordering claim is made: the observed range does not "
                    "sit cleanly between the two reference conditions."
                )
                + "\n"
            )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(L))
    print(f"Wrote {args.out} ({len(found)} condition(s)"
          + (f", missing: {', '.join(missing)}" if missing else "") + ")")


if __name__ == "__main__":
    main()
